# Generated by Django 4.2.7 on 2023-12-03 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('acronym', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='conference_thumbnails/')),
                ('submission_satrt', models.DateTimeField()),
                ('submission_deadline', models.DateTimeField()),
                ('conference_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.CharField(blank=True, max_length=500, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('organizers', models.ManyToManyField(related_name='conferences_organized', to=settings.AUTH_USER_MODEL)),
                ('reviewers', models.ManyToManyField(related_name='conferences_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
