# Generated by Django 4.2.7 on 2023-12-03 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='submission_satrt',
            new_name='submission_start',
        ),
    ]
