# Generated by Django 4.2.7 on 2023-12-04 01:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conference', '0002_rename_submission_satrt_conference_submission_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='reviewers',
            field=models.ManyToManyField(blank=True, null=True, related_name='conferences_reviewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
