# Generated by Django 4.2.7 on 2023-12-03 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='papers/')),
                ('status', models.CharField(default='submitted', max_length=50)),
                ('reviews', models.TextField(blank=True, null=True)),
                ('authors', models.ManyToManyField(related_name='papers_authored', to=settings.AUTH_USER_MODEL)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='conference.conference')),
                ('reviewers', models.ManyToManyField(related_name='papers_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
