# Generated by Django 4.2.7 on 2023-12-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='alignment_with_scope',
            field=models.IntegerField(blank=True, choices=[(5, 'Very High'), (4, 'High'), (3, 'Moderate'), (2, 'Low'), (1, 'Very Low')], null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='annotated_pdf',
            field=models.FileField(blank=True, null=True, upload_to='annotated_pdfs/'),
        ),
        migrations.AddField(
            model_name='review',
            name='comments_to_authors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comments_to_editors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='contribution_to_field',
            field=models.IntegerField(blank=True, choices=[(5, 'Very Significant'), (4, 'Significant'), (3, 'Moderate'), (2, 'Limited'), (1, 'Negligible')], null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='ethical_considerations',
            field=models.IntegerField(blank=True, choices=[(5, 'Fully Addressed'), (4, 'Addressed'), (3, 'Partially Addressed'), (2, 'Somehow Addressed'), (1, 'Not Addressed')], null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='introduction_quality',
            field=models.IntegerField(blank=True, choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Adequate'), (2, 'Needs Improvement'), (1, 'Bad')], null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='literature_review_quality',
            field=models.IntegerField(blank=True, choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Adequate'), (2, 'Needs Improvement'), (1, 'Bad')], null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='methodology_quality',
            field=models.IntegerField(blank=True, choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Adequate'), (2, 'Needs Improvement'), (1, 'Bad')], null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='originality',
            field=models.IntegerField(blank=True, choices=[(5, 'Very High'), (4, 'High'), (3, 'Moderate'), (2, 'Low'), (1, 'Very Low')], null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='overall_recommendation',
            field=models.CharField(blank=True, choices=[('accept_as_is', 'Accept as Is'), ('accept_with_minor_revisions', 'Accept with Minor Revisions'), ('accept_with_major_revisions', 'Accept with Major Revisions'), ('reject', 'Reject')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='references_and_citations_quality',
            field=models.IntegerField(blank=True, choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Fair'), (2, 'Poor'), (1, 'Very Poor')], null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='results_clarity_and_validity',
            field=models.IntegerField(blank=True, choices=[(5, 'Very High'), (4, 'High'), (3, 'Moderate'), (2, 'Low'), (1, 'Very Low')], null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='writing_and_organization',
            field=models.IntegerField(blank=True, choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Adequate'), (2, 'Needs Improvement'), (1, 'Bad')], null=True),
        ),
    ]
